import type { PropertyCandidate } from "./types";

export const propertyCandidates: PropertyCandidate[] = [
  {
    id: "mission-bay-condo",
    name: "Mission Bay Condo",
    address: "435 China Basin Street, Unit 502",
    market: "San Francisco, CA",
    neighborhood: "Mission Bay",
    zipCode: "94158",
    propertyType: "Condo",
    bedroomCount: 1,
    bathroomCount: 1,
    squareFeet: 760,
    status: "Diligence",
    strategy: "Primary-residence hosted STR",
    source: "Prototype listing feed",
    purchasePrice: 1100000,
    currentEstimatedValue: 1180000,
    estimatedNightlyRate: 265,
    occupancyRate: 0.68,
    cleaningFeesMonthly: 520,
    platformFeesMonthly: 520,
    managementFeesMonthly: 980,
    taxesInsuranceUtilitiesMonthly: 1820,
    maintenanceReserveMonthly: 450,
    estimatedMonthlyDebtService: 5200,
    cashInvested: 275000,
    minimumDownPayment: 250000,
    targetCapRate: 0.045,
    targetCashOnCashReturn: 0.055,
    targetAnnualAppreciation: 0.041,
    riskRating: "Moderate",
    strRegistrationLikely: true,
    hoaAllowsShortTermRental: false,
    estimatedUnhostedNights: 72,
    zoningNotes: "Mixed-use neighborhood with elevated condo HOA review risk.",
    complianceNotes: [
      "Validate HOA rental language before underwriting.",
      "Assumes owner can satisfy San Francisco primary-residence requirements.",
    ],
    mapPosition: { x: 64, y: 62 },
    neighborhoodInsight: {
      description:
        "Mission Bay offers newer housing stock, strong medical and life-science employment demand, and cleaner building condition than many legacy neighborhoods.",
      pros: ["Newer inventory", "Transit and employment anchors", "Strong renter demand"],
      cons: ["HOA diligence required", "High acquisition basis", "Limited historic charm premium"],
      news: [
        {
          date: "2026",
          headline: "Life-science and medical anchors continue to support demand.",
          source: "Prototype market note",
        },
      ],
    },
    valueHistory: [
      { period: "2021", value: 1060000 },
      { period: "2022", value: 1125000 },
      { period: "2023", value: 1150000 },
      { period: "2024", value: 1168000 },
      { period: "2025", value: 1180000 },
    ],
  },
  {
    id: "noe-valley-garden-suite",
    name: "Noe Valley Garden Suite",
    address: "1428 Sanchez Street",
    market: "San Francisco, CA",
    neighborhood: "Noe Valley",
    zipCode: "94114",
    propertyType: "Single-family",
    bedroomCount: 2,
    bathroomCount: 1,
    squareFeet: 1080,
    status: "Live",
    strategy: "Hosted suite with owner occupancy",
    source: "Prototype comp set",
    purchasePrice: 1580000,
    currentEstimatedValue: 1695000,
    estimatedNightlyRate: 315,
    occupancyRate: 0.64,
    cleaningFeesMonthly: 620,
    platformFeesMonthly: 600,
    managementFeesMonthly: 1080,
    taxesInsuranceUtilitiesMonthly: 2350,
    maintenanceReserveMonthly: 720,
    estimatedMonthlyDebtService: 7050,
    cashInvested: 395000,
    minimumDownPayment: 360000,
    targetCapRate: 0.043,
    targetCashOnCashReturn: 0.052,
    targetAnnualAppreciation: 0.048,
    riskRating: "Conservative",
    strRegistrationLikely: true,
    hoaAllowsShortTermRental: true,
    estimatedUnhostedNights: 64,
    zoningNotes: "Residential neighborhood with stronger owner-occupancy fit.",
    complianceNotes: [
      "Best fit when investor plans to occupy the property as a primary residence.",
      "Confirm registration, business account, and tax collection requirements.",
    ],
    mapPosition: { x: 45, y: 56 },
    neighborhoodInsight: {
      description:
        "Noe Valley is a premium residential market with durable family demand, walkable retail corridors, and comparatively lower operating volatility.",
      pros: ["Premium residential demand", "Walkable retail", "Conservative risk fit"],
      cons: ["High entry cost", "Lower yield than emerging areas", "Owner-occupancy assumption matters"],
      news: [
        {
          date: "2026",
          headline: "Family-oriented neighborhoods remain resilient in SF pricing.",
          source: "Prototype market note",
        },
      ],
    },
    valueHistory: [
      { period: "2021", value: 1470000 },
      { period: "2022", value: 1545000 },
      { period: "2023", value: 1610000 },
      { period: "2024", value: 1665000 },
      { period: "2025", value: 1695000 },
    ],
  },
  {
    id: "north-beach-flat",
    name: "North Beach Flat",
    address: "840 Green Street, Unit 3",
    market: "San Francisco, CA",
    neighborhood: "North Beach",
    zipCode: "94133",
    propertyType: "Condo",
    bedroomCount: 1,
    bathroomCount: 1,
    squareFeet: 690,
    status: "Watchlist",
    strategy: "Urban visitor demand",
    source: "Prototype listing feed",
    purchasePrice: 950000,
    currentEstimatedValue: 918000,
    estimatedNightlyRate: 235,
    occupancyRate: 0.7,
    cleaningFeesMonthly: 460,
    platformFeesMonthly: 500,
    managementFeesMonthly: 890,
    taxesInsuranceUtilitiesMonthly: 1550,
    maintenanceReserveMonthly: 420,
    estimatedMonthlyDebtService: 4580,
    cashInvested: 237500,
    minimumDownPayment: 215000,
    targetCapRate: 0.044,
    targetCashOnCashReturn: 0.05,
    targetAnnualAppreciation: 0.024,
    riskRating: "Aggressive",
    strRegistrationLikely: true,
    hoaAllowsShortTermRental: false,
    estimatedUnhostedNights: 108,
    zoningNotes: "Tourism demand is strong, but condo restrictions need review.",
    complianceNotes: [
      "Estimated unhosted nights exceed the conservative San Francisco policy guardrail.",
      "HOA restrictions create a high diligence burden.",
    ],
    mapPosition: { x: 50, y: 25 },
    neighborhoodInsight: {
      description:
        "North Beach has strong visitor appeal and restaurant density, but condo governance and unhosted-night assumptions need careful review.",
      pros: ["Visitor demand", "Dining and nightlife", "Central location"],
      cons: ["HOA restriction risk", "Higher noise exposure", "Unhosted-night diligence"],
      news: [
        {
          date: "2026",
          headline: "Visitor corridors continue to outperform on nightly demand.",
          source: "Prototype market note",
        },
      ],
    },
    valueHistory: [
      { period: "2021", value: 955000 },
      { period: "2022", value: 970000 },
      { period: "2023", value: 948000 },
      { period: "2024", value: 930000 },
      { period: "2025", value: 918000 },
    ],
  },
  {
    id: "sunset-duplex",
    name: "Outer Sunset Duplex",
    address: "1834 44th Avenue",
    market: "San Francisco, CA",
    neighborhood: "Outer Sunset",
    zipCode: "94122",
    propertyType: "Duplex",
    bedroomCount: 3,
    bathroomCount: 2,
    squareFeet: 1840,
    status: "Diligence",
    strategy: "House-hack with hosted unit",
    source: "Prototype broker lead",
    purchasePrice: 1360000,
    currentEstimatedValue: 1435000,
    estimatedNightlyRate: 225,
    occupancyRate: 0.61,
    cleaningFeesMonthly: 610,
    platformFeesMonthly: 420,
    managementFeesMonthly: 760,
    taxesInsuranceUtilitiesMonthly: 2050,
    maintenanceReserveMonthly: 820,
    estimatedMonthlyDebtService: 6400,
    cashInvested: 340000,
    minimumDownPayment: 310000,
    targetCapRate: 0.046,
    targetCashOnCashReturn: 0.054,
    targetAnnualAppreciation: 0.039,
    riskRating: "Moderate",
    strRegistrationLikely: true,
    hoaAllowsShortTermRental: true,
    estimatedUnhostedNights: 86,
    zoningNotes: "Duplex structure supports owner-occupancy scenarios.",
    complianceNotes: [
      "Confirm unit-level eligibility and no prior eviction restrictions.",
      "Model hosted and unhosted scenarios separately.",
    ],
    mapPosition: { x: 18, y: 55 },
    neighborhoodInsight: {
      description:
        "Outer Sunset offers more space, coastal appeal, and house-hack potential, with demand driven by families, beach access, and longer leisure stays.",
      pros: ["Larger layouts", "Coastal demand", "Duplex flexibility"],
      cons: ["Seasonal demand swings", "Longer downtown commute", "Weather discount"],
      news: [
        {
          date: "2026",
          headline: "West-side homes retain buyer interest on space and access.",
          source: "Prototype market note",
        },
      ],
    },
    valueHistory: [
      { period: "2021", value: 1265000 },
      { period: "2022", value: 1320000 },
      { period: "2023", value: 1375000 },
      { period: "2024", value: 1410000 },
      { period: "2025", value: 1435000 },
    ],
  },
  {
    id: "soma-loft",
    name: "SoMa Loft",
    address: "655 5th Street, Loft 12",
    market: "San Francisco, CA",
    neighborhood: "SoMa",
    zipCode: "94103",
    propertyType: "Condo",
    bedroomCount: 1,
    bathroomCount: 1,
    squareFeet: 820,
    status: "Watchlist",
    strategy: "Business travel demand",
    source: "Prototype listing feed",
    purchasePrice: 1040000,
    currentEstimatedValue: 985000,
    estimatedNightlyRate: 255,
    occupancyRate: 0.58,
    cleaningFeesMonthly: 510,
    platformFeesMonthly: 450,
    managementFeesMonthly: 850,
    taxesInsuranceUtilitiesMonthly: 1700,
    maintenanceReserveMonthly: 500,
    estimatedMonthlyDebtService: 4920,
    cashInvested: 260000,
    minimumDownPayment: 235000,
    targetCapRate: 0.045,
    targetCashOnCashReturn: 0.052,
    targetAnnualAppreciation: 0.022,
    riskRating: "Aggressive",
    strRegistrationLikely: false,
    hoaAllowsShortTermRental: false,
    estimatedUnhostedNights: 120,
    zoningNotes: "High regulatory and HOA friction for non-owner STR use.",
    complianceNotes: [
      "Registration likelihood is low under current prototype assumptions.",
      "Short-term rental policy risk should dominate underwriting.",
    ],
    mapPosition: { x: 56, y: 49 },
    neighborhoodInsight: {
      description:
        "SoMa can produce strong business-travel demand, but office-market uncertainty and HOA restrictions create a narrow recommendation path.",
      pros: ["Business-travel access", "Central location", "Transit proximity"],
      cons: ["Registration risk", "Office-market uncertainty", "HOA friction"],
      news: [
        {
          date: "2026",
          headline: "Downtown-adjacent demand remains uneven by block and asset type.",
          source: "Prototype market note",
        },
      ],
    },
    valueHistory: [
      { period: "2021", value: 1085000 },
      { period: "2022", value: 1060000 },
      { period: "2023", value: 1030000 },
      { period: "2024", value: 1005000 },
      { period: "2025", value: 985000 },
    ],
  },
  {
    id: "bernal-heights-home",
    name: "Bernal Heights Home",
    address: "318 Gates Street",
    market: "San Francisco, CA",
    neighborhood: "Bernal Heights",
    zipCode: "94110",
    propertyType: "Single-family",
    bedroomCount: 2,
    bathroomCount: 1,
    squareFeet: 1125,
    status: "Live",
    strategy: "Hosted family stay",
    source: "Prototype comp set",
    purchasePrice: 1280000,
    currentEstimatedValue: 1365000,
    estimatedNightlyRate: 275,
    occupancyRate: 0.66,
    cleaningFeesMonthly: 560,
    platformFeesMonthly: 540,
    managementFeesMonthly: 940,
    taxesInsuranceUtilitiesMonthly: 1980,
    maintenanceReserveMonthly: 650,
    estimatedMonthlyDebtService: 5980,
    cashInvested: 320000,
    minimumDownPayment: 292000,
    targetCapRate: 0.044,
    targetCashOnCashReturn: 0.053,
    targetAnnualAppreciation: 0.045,
    riskRating: "Moderate",
    strRegistrationLikely: true,
    hoaAllowsShortTermRental: true,
    estimatedUnhostedNights: 70,
    zoningNotes: "Owner-occupied single-family profile fits the narrow SF STR path.",
    complianceNotes: [
      "Confirm primary-residence evidence before recommending.",
      "Track local registration and tax remittance workflow.",
    ],
    mapPosition: { x: 52, y: 68 },
    neighborhoodInsight: {
      description:
        "Bernal Heights combines owner-occupant appeal, neighborhood character, and balanced appreciation potential with fewer HOA constraints.",
      pros: ["Single-family control", "Neighborhood character", "Balanced return profile"],
      cons: ["Limited inventory", "High insurance and tax load", "Primary-residence proof required"],
      news: [
        {
          date: "2026",
          headline: "Owner-occupant neighborhoods remain a core SF underwriting theme.",
          source: "Prototype market note",
        },
      ],
    },
    valueHistory: [
      { period: "2021", value: 1200000 },
      { period: "2022", value: 1265000 },
      { period: "2023", value: 1310000 },
      { period: "2024", value: 1348000 },
      { period: "2025", value: 1365000 },
    ],
  },
];
